syntax on
set tabstop=4
set expandtab
set number
set wrap
set encoding=utf-8
set showmatch
set visualbell
set autoindent
set smartindent
set shiftwidth=4
set softtabstop=4
set nocompatible
set clipboard=unnamed
set wildmenu
set esckeys
set backspace=indent,eol,start
set ttyfast
set gdefault
set binary
set noeol
set incsearch
set hlsearch
set cursorline
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list
set nostartofline
set showmode
set title
set showcmd
set t_Co=256

autocmd FileType yaml,yml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType cpp,cc setlocal ts=2 sts=2 sw=2 expandtab
autocmd BufRead,BufNewFile *.C set filetype=cpp
autocmd BufRead,BufNewFile storage.conf,containers.conf,registries.conf set filetype=toml

" Install vim-plug if not installed
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Appearance
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'romainl/vim-cool'

" Syntax highlighting and formatting
Plug 'JuliaEditorSupport/julia-vim'
Plug 'dense-analysis/ale'
Plug 'plasticboy/vim-markdown'
Plug 'elzr/vim-json'
Plug 'cespare/vim-toml'

" Productivity
Plug 'tpope/vim-surround'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'machakann/vim-highlightedyank'
Plug 'tpope/vim-fugitive'

" Additional features
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-dispatch'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()

" Theme
colorscheme dracula
