syntax on
set tabstop=4
set expandtab
set number
set wrap
set encoding=utf-8
set showmatch
set visualbell

set autoindent
set smartindent
set shiftwidth=4
set softtabstop=4

set incsearch
set hlsearch

set t_Co=256

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType yml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType cpp setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=2
autocmd FileType cc setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=2

autocmd BufRead,BufNewFile *.C set filetype=cpp
autocmd BufRead,BufNewFile storage.conf set filetype=toml
autocmd BufRead,BufNewFile containers.conf set filetype=toml
autocmd BufRead,BufNewFile registries.conf set filetype=toml

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'JuliaEditorSupport/julia-vim'
Plug 'tpope/vim-surround'
Plug 'terryma/vim-smooth-scroll'
Plug 'ap/vim-css-color'
Plug 'mattn/emmet-vim'
Plug 'mhinz/vim-startify'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'romainl/vim-cool'
Plug 'tpope/vim-endwise'
Plug 'rstacruz/vim-closer'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'junegunn/vim-easy-align'
Plug 'machakann/vim-highlightedyank'
Plug 'ntpeters/vim-better-whitespace'
Plug 'cespare/vim-toml'
call plug#end()
