source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh #Uncomment for Mac Homebrew
#source ${ZDOTDIR:-~}/.antidote/antidote.zsh #Uncomment for Linux

antidote load

PS1='%m %~%# '

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
